- name: Install docker
  hosts: remote-server
  gather_facts: no
  become: true

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install java
      yum:
        name: java-1.8.0
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
    
    - name: Install python docker
      yum:
        name: python-docker-py

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Install and upgrade pip
      yum:
        name: python3-pip
        name: python3
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull default Docker image
      docker_image:
        name: jenkins/jenkins
        source: pull

    - name: Create jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins
        state: present

    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Add user remote-host to docker group
      user:
        name: remote-host
        groups: docker
        append: yes

